package com.wl.pluto.plutochat.chat.greedao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.wl.pluto.plutochat.chat.entity.NearbyPeopleEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig nearbyPeopleEntityDaoConfig;

    private final NearbyPeopleEntityDao nearbyPeopleEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        nearbyPeopleEntityDaoConfig = daoConfigMap.get(NearbyPeopleEntityDao.class).clone();
        nearbyPeopleEntityDaoConfig.initIdentityScope(type);

        nearbyPeopleEntityDao = new NearbyPeopleEntityDao(nearbyPeopleEntityDaoConfig, this);

        registerDao(NearbyPeopleEntity.class, nearbyPeopleEntityDao);
    }
    
    public void clear() {
        nearbyPeopleEntityDaoConfig.getIdentityScope().clear();
    }

    public NearbyPeopleEntityDao getNearbyPeopleEntityDao() {
        return nearbyPeopleEntityDao;
    }

}
